{% set name = "tfs-pandas" %}
{% set version = "3.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: be6be972407274053cbea8da821414626098074b573709f15d5836e707d09a24

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - numpy >=1.24
    - pandas >=2.1

test:
  imports:
    - tfs
    - tfs.frame
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pylhc/tfs
  summary: Python 3 package to handle TFS files.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A wrapper around pandas DataFrames to handle TFS files.
  doc_url: https://pylhc.github.io/tfs/

extra:
  recipe-maintainers:
    - fsoubelet
