{% set name = "tfs-pandas" %}
{% set version = "3.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tfs-pandas-{{ version }}.tar.gz
  sha256: 53d44295c1ea1e6963488e9012b3612f4f0bf8d84ea1abbc368d8fc8bdbd86a9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.19.0
    - pandas >=1.0
    - python >=3.6

test:
  imports:
    - tfs
    - tfs.frame
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pylhc/tfs
  summary: Python 3 package to handle TFS files.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A wrapper around pandas DataFrames to handle TFS files.
  doc_url: https://pylhc.github.io/tfs/

extra:
  recipe-maintainers:
    - fsoubelet
