{% set name = "tfs-pandas" %}
{% set version = "3.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 06204a9629f3007148b46d4d0922c028644b6e3d8063fb16cb3db7cc1e9d7630

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - pandas >=2.1

test:
  imports:
    - tfs
    - tfs.frame
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pylhc/tfs
  summary: Python 3 package to handle TFS files.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A wrapper around pandas DataFrames to handle TFS files.
  doc_url: https://pylhc.github.io/tfs/

extra:
  recipe-maintainers:
    - fsoubelet
